Fix html parsing to allow assessed feature without exercises
Running "rake sprint:007a" was giving the following error:

```
rake aborted!
NoMethodError: undefined method `parent' for nil:NilClass
/home/karen/tutor-server/lib/html_tree_operations.rb:7:in `recursive_compact'
/home/karen/tutor-server/app/external/openstax/cnx/v1/page.rb:132:in `fragments'
```

because we just added this page
http://cnx.org/contents/7db9aa72-f815-4c3b-9cb6-d50cf5318b58@4.5:2/Updated_Tutor_HS_Physics_Conte#fs-id1172194442505
which has an assessed feature with just a video without an exercise.